# Default configuration for multimodal recommender

model:
  vision_model: clip  # Options: clip, dino, resnet, convnext
  language_model: sentence-bert  # Options: sentence-bert, mpnet, bert, roberta
  embedding_dim: 128
  freeze_vision: true
  freeze_language: true
  use_contrastive: true
  dropout_rate: 0.3

training:
  batch_size: 32
  epochs: 10
  learning_rate: 0.001
  weight_decay: 0.01
  patience: 3
  gradient_clip: 1.0
  num_workers: 4
  contrastive_weight: 0.1
  bce_weight: 1.0

data:
  item_info_path: data/raw/item_info/Pixel200K.csv
  interactions_path: data/raw/interactions/Pixel200K.csv
  image_folder: data/raw/images
  sample_size: 10000  # Set to null for full dataset
  negative_sampling_ratio: 1.0
  train_val_split: 0.8

recommendation:
  top_k: 10
  diversity_weight: 0.3
  novelty_weight: 0.2
  filter_seen: true
  max_candidates: 1000

# Paths
checkpoint_dir: models/checkpoints
log_dir: logs/tensorboard
results_dir: results