# Default configuration for multimodal recommender

model:
  vision_model: clip # clip, resnet, vit
  language_model: sentence-bert
  embedding_dim: 64
  freeze_vision: true
  freeze_language: true
  use_contrastive: true
  dropout_rate: 0.3

training:
  batch_size: 64
  epochs: 30
  learning_rate: 0.001
  weight_decay: 0.01
  patience: 10
  gradient_clip: 1.0
  num_workers: 8
  contrastive_weight: 0.1
  bce_weight: 1.0

data:
  item_info_path: data/raw/item_info/Pixel200K.csv # Path to original raw item metadata
  interactions_path: data/raw/interactions/Pixel200K.csv # Path to original raw interactions
  image_folder: data/raw/images # Path to folder containing item images

  # Paths for processed data (output of scripts/preprocess_data.py)
  processed_item_info_path: data/processed/item_info_processed.csv
  processed_interactions_path: data/processed/interactions_processed.csv
  scaler_path: data/processed/numerical_scaler.pkl # Path to save/load the fitted numerical scaler

  sample_size: 5000  # Set to null for full dataset, applied to processed data in train script
  negative_sampling_ratio: 1.0
  train_val_split: 0.8

  numerical_features_cols: # List of numerical feature column names from item_info_df
    - view_number
    - comment_number
    - thumbup_number
    - share_number
    - coin_number
    - favorite_number
    - barrage_number
  
  numerical_normalization_method: 'standardization' # 'log1p', 'standardization', 'min_max', 'none'

  text_augmentation:
    enabled: true # Enable text augmentation for training
    augmentation_type: 'random_delete' # 'random_delete', 'random_swap', 'none'
    delete_prob: 0.05
    swap_prob: 0.05

  offline_image_validation:
    check_corrupted: true
    min_width: 64
    min_height: 64
    allowed_extensions: ['.jpg', '.jpeg', '.png']

  offline_text_cleaning:
    remove_html: true
    normalize_unicode: true
    to_lowercase: true

  # Data splitting configuration
  splitting:
    strategy: 'stratified'
    train_ratio: 0.8
    random_state: 42
    min_interactions_per_user: 2 
    min_interactions_per_item: 2   
    timestamp_col: null
    leave_one_out_strategy: 'random'
    cold_user_ratio: 0.1
    cold_item_ratio: 0.1
    validate_no_leakage: true

recommendation:
  top_k: 10
  diversity_weight: 0.3
  novelty_weight: 0.2
  filter_seen: true
  max_candidates: 1000

# Paths
checkpoint_dir: models/checkpoints
results_dir: results
# Removed: log_dir (was for TensorBoard)