# Default configuration for multimodal recommender

model:
  # Model selection
  model_class: pretrained  # Options: 'pretrained' or 'enhanced'
  vision_model: clip       # Options: clip, resnet, dino, convnext
  language_model: sentence-bert  # Options: sentence-bert, mpnet, bert, roberta
  
  # Core parameters
  embedding_dim: 64
  freeze_vision: true
  freeze_language: true
  
  # Contrastive learning
  use_contrastive: true
  contrastive_temperature: 0.07
  
  # Regularization
  dropout_rate: 0.3
  
  # Attention mechanism
  num_attention_heads: 4
  attention_dropout: 0.1
  
  # Fusion network architecture
  fusion_hidden_dims: [512, 256, 128]  # List of hidden layer dimensions
  fusion_activation: relu  # Options: relu, gelu, tanh, leaky_relu, silu
  use_batch_norm: true
  
  # Projection layers
  projection_hidden_dim: null  # Set to integer to add hidden layer in projections
  
  # Cross-modal attention (for enhanced model)
  use_cross_modal_attention: true
  cross_modal_attention_weight: 0.5
  
  # Other architectural choices
  final_activation: sigmoid  # Options: sigmoid, tanh, none
  init_method: xavier_uniform  # Options: xavier_uniform, xavier_normal, kaiming_uniform, kaiming_normal

training:
  # Basic training parameters
  batch_size: 64
  epochs: 30
  learning_rate: 0.001
  weight_decay: 0.01
  patience: 10
  gradient_clip: 1.0
  num_workers: 4
  
  # Loss weights
  contrastive_weight: 0.1
  bce_weight: 1.0
  
  # Learning rate scheduling
  use_lr_scheduler: true
  lr_scheduler_type: reduce_on_plateau  # Options: reduce_on_plateau, cosine, step
  lr_scheduler_patience: 2
  lr_scheduler_factor: 0.5
  lr_scheduler_min_lr: 0.000001
  
  # Optimizer settings
  optimizer_type: adamw  # Options: adamw, adam, sgd
  adam_beta1: 0.9
  adam_beta2: 0.999
  adam_eps: 0.00000001

data:
  # Data paths
  item_info_path: data/raw/item_info/Pixel200K.csv
  interactions_path: data/raw/interactions/Pixel200K.csv
  image_folder: data/raw/images
  
  # Processed data paths
  processed_item_info_path: data/processed/item_info_processed.csv
  processed_interactions_path: data/processed/interactions_processed.csv
  scaler_path: data/processed/numerical_scaler.pkl
  
  # Data sampling and processing
  sample_size: 5000  # Set to null for full dataset
  negative_sampling_ratio: 1.0
  train_val_split: 0.8
  
  # Numerical features
  numerical_features_cols:
    - view_number
    - comment_number
    - thumbup_number
    - share_number
    - coin_number
    - favorite_number
    - barrage_number
  
  numerical_normalization_method: standardization  # Options: log1p, standardization, min_max, none
  
  # Text augmentation
  text_augmentation:
    enabled: true
    augmentation_type: random_delete  # Options: random_delete, random_swap, none
    delete_prob: 0.05
    swap_prob: 0.05
  
  # Offline image validation
  offline_image_validation:
    check_corrupted: true
    min_width: 64
    min_height: 64
    allowed_extensions: ['.jpg', '.jpeg', '.png']
  
  # Offline text cleaning
  offline_text_cleaning:
    remove_html: true
    normalize_unicode: true
    to_lowercase: true
  
  # Data splitting configuration
  splitting:
    strategy: stratified  # Options: stratified, user, item, temporal, leave_one_out, simple_random
    train_ratio: 0.8
    random_state: 42
    min_interactions_per_user: 2
    min_interactions_per_item: 2
    timestamp_col: null  # Required for temporal split
    leave_one_out_strategy: random  # Options: random, latest
    cold_user_ratio: 0.1  # For mixed split
    cold_item_ratio: 0.1  # For mixed split
    validate_no_leakage: true

recommendation:
  top_k: 10
  diversity_weight: 0.3
  novelty_weight: 0.2
  filter_seen: true
  max_candidates: 1000

# Paths
checkpoint_dir: models/checkpoints
results_dir: results