name: CI Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        # Clones the repository, making its contents available to the workflow.

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.8' # Specifies the Python version to use for the environment.
          cache: 'pip' # Enables caching for pip dependencies to speed up subsequent runs.

      - name: Install dependencies
        run: |
          pip install torch==2.2.1 torchvision==0.17.1 torchaudio==2.2.1 --index-url https://download.pytorch.org/whl/cpu
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Run tests with coverage
        run: |
          # Executes the tests using pytest, including coverage reporting.
          # The --cov=src argument tells pytest-cov to collect coverage data for the 'src' directory.
          # The --cov-report=xml argument generates a Cobertura-format XML report for integration with other tools (e.g., Codecov).
          # The --cov-report=term-missing argument displays missing lines in the terminal output.
          pytest tests/ --cov=src --cov-report=xml --cov-report=term-missing